### ISSUE TITLE
Show loading state on timed-admin 

### ISSUE THREAD

**Issue by Yelinz** [adfinis/customer-center#115] opened 2020-01-24 15:41 UTC
Load all project on timed-admin view when initial render was in timed-admin/detail view.

**Comment by Yelinz** [comment] 2020-01-27 10:03
Actually works, just takes a second and it is not indicated that it is loading

**Comment by velrest** [comment] 2020-02-10 09:19
So the issue is actually missing user feedback?

**Comment by Yelinz** [comment] 2020-02-10 09:29
Afaik yes

**Comment by velrest** [comment] 2020-02-10 09:39
Then shall we rename the issue or open a new one?

**Comment by fkm-adfinis** [comment] 2021-01-08 12:39
I'll have a look at this issue. We still have the same problem after the rewrite. It seems that in some cases the loading template is not rendered even if it is the request that takes long and not the parsing of the response in the controller.

**Comment by fkm-adfinis** [comment] 2021-03-23 14:58
I never figured out, why the loading animation/template isn't shown for some routes. This problem is especially problematic on `/subscriptions/list` as the request can take a long time.

**Comment by velrest** [comment] 2022-12-14 09:10
This should be fixed with the redesign.

**Closed by velrest** 2022-12-14 09:10 UTC
Labels: bug
